name: CI
on:
  push:
jobs:
  # Job that runs eslint on the project, this can fail on linting
  # errors that can't be autofixed and will fail if autofixed issues are
  # not committed
  lint:
    runs-on: ubuntu-latest
    container: "node:10.15"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Lint UI
        run: yarn lint
      - name: Check for changes
        run: git diff --exit-code

  # Job that builds and bundles the extension, changes mode based on git branch
  build:
    runs-on: ubuntu-latest
    container: "node:10.15"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      - name: Build extension
        if: github.ref != 'refs/heads/master'
        run: yarn dev
      - name: Build extension
        if: github.ref == 'refs/heads/master'
        run: yarn prod
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        if: github.ref == 'refs/heads/master'
        with:
          name: extension
          path: dist
